version: '3' 
services:
    redis-server:
        image: 'redis'
    node-app:
    # . current folder
    # mapping the node app to redis server
        build: .
        ports:
            - "8081:8081"
